modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All Rights Reserved"
[[mods]] #mandatory
# The modid of the mod
modId="experiencedworlds" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Experienced Worlds" #mandatory
authors="Drathonix" #optional
description='''
The world expands the more you experience it.
'''
[[dependencies.experiencedworlds]] #optional
    modId="serverstatistics" #mandatory
    mandatory=true #mandatory
    versionRange="[1.18.2-1.0.7,)" #mandatory
    ordering="AFTER"
    side="BOTH"
